# Generated by Django 5.2.16 on 2026-07-17 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoPerdido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('num', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('imagen', models.ImageField(blank=True, upload_to='objetos_perdidos/')),
                ('fecha_reporte', models.DateField(blank=True, null=True)),
                ('fecha_encontrado', models.DateField(blank=True, null=True)),
                ('fecha_devuelto', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('privada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetos_perdidos', to='communities.privada')),
                ('recuperador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos_recuperados', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetos_reportados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'objeto perdido',
                'verbose_name_plural': 'objetos perdidos',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['privada', 'tipo'], name='objetos_per_privada_c40a48_idx')],
            },
        ),
    ]
