# Generated by Django 5.2.17 on 2026-08-10 05:41

import apps.objetos_perdidos.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def migrar_objetos_existentes(apps, schema_editor):
    Objeto = apps.get_model('objetos_perdidos', 'ObjetoPerdido')
    Objeto.objects.filter(tipo='perdido').update(tipo='extraviado')
    Objeto.objects.filter(tipo='encontrado').update(tipo='resguardado')
    Objeto.objects.filter(fecha_devuelto__isnull=False, tipo='extraviado').update(estado_caso='recuperado')
    Objeto.objects.filter(fecha_devuelto__isnull=False, tipo='resguardado').update(estado_caso='entregado')
    for objeto in Objeto.objects.filter(tipo='resguardado', responsable_resguardo__isnull=True):
        objeto.responsable_resguardo_id = objeto.reportado_por_id
        objeto.save(update_fields=('responsable_resguardo',))


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_reglamento'),
        ('objetos_perdidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaObjeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmacion_entrega', models.BooleanField(default=False)),
                ('confirmacion_recepcion', models.BooleanField(default=False)),
                ('codigo_temporal', models.CharField(default=apps.objetos_perdidos.models.generar_codigo_entrega, max_length=6)),
                ('codigo_expira_en', models.DateTimeField()),
                ('codigo_usado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaPropiedad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='objetos_perdidos/evidencias/')),
                ('descripcion', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreguntaValidacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('pregunta', models.CharField(max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('orden', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('informacion_requerida', 'Información adicional requerida'), ('aprobada', 'Reclamación aprobada'), ('rechazada', 'Reclamación rechazada'), ('entregada', 'Objeto entregado')], db_index=True, default='pendiente', max_length=24)),
                ('mensaje', models.TextField(blank=True)),
                ('notas_revision', models.TextField(blank=True)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RespuestaValidacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('respuesta', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='objetoperdido',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveIndex(
            model_name='objetoperdido',
            name='objetos_per_privada_c40a48_idx',
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='detalles_privados',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='estado_caso',
            field=models.CharField(choices=[('activo', 'Activo'), ('posiblemente_localizado', 'Posiblemente localizado'), ('reclamacion_en_revision', 'Reclamación en revisión'), ('recuperado', 'Objeto recuperado'), ('entregado', 'Entregado a su propietario'), ('cerrado', 'Cerrado')], db_index=True, default='activo', max_length=32),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='fecha_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='informacion_adicional',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='lugar_resguardo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='posible_localizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos_posiblemente_localizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='responsable_resguardo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos_resguardados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objetoperdido',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='objetoperdido',
            name='tipo',
            field=models.CharField(choices=[('extraviado', 'Objeto extraviado'), ('resguardado', 'Objeto resguardado')], default='extraviado', max_length=15),
        ),
        migrations.RunPython(migrar_objetos_existentes, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='objetoperdido',
            index=models.Index(fields=['privada', 'tipo', 'estado_caso'], name='objetos_per_privada_ebeb6a_idx'),
        ),
        migrations.AddField(
            model_name='entregaobjeto',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregaobjeto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregaobjeto',
            name='entregado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregaobjeto',
            name='objeto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrega', to='objetos_perdidos.objetoperdido'),
        ),
        migrations.AddField(
            model_name='entregaobjeto',
            name='recibido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregaobjeto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciapropiedad',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciapropiedad',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preguntavalidacion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preguntavalidacion',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_validacion', to='objetos_perdidos.objetoperdido'),
        ),
        migrations.AddField(
            model_name='preguntavalidacion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones', to='objetos_perdidos.objetoperdido'),
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones_objetos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciapropiedad',
            name='reclamacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='objetos_perdidos.reclamacion'),
        ),
        migrations.AddField(
            model_name='entregaobjeto',
            name='reclamacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrega', to='objetos_perdidos.reclamacion'),
        ),
        migrations.AddField(
            model_name='respuestavalidacion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestavalidacion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='objetos_perdidos.preguntavalidacion'),
        ),
        migrations.AddField(
            model_name='respuestavalidacion',
            name='reclamacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='objetos_perdidos.reclamacion'),
        ),
        migrations.AddField(
            model_name='respuestavalidacion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='preguntavalidacion',
            constraint=models.UniqueConstraint(fields=('objeto', 'orden'), name='uq_pregunta_objeto_orden'),
        ),
        migrations.AddConstraint(
            model_name='reclamacion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'activo')), fields=('objeto', 'solicitante'), name='uq_reclamacion_activa_objeto_usuario'),
        ),
        migrations.AddConstraint(
            model_name='respuestavalidacion',
            constraint=models.UniqueConstraint(fields=('reclamacion', 'pregunta'), name='uq_respuesta_reclamacion_pregunta'),
        ),
    ]
