# Generated by Django 5.2.17 on 2026-08-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetos_perdidos', '0002_entregaobjeto_evidenciapropiedad_preguntavalidacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetoperdido',
            name='lugar_resguardo',
        ),
    ]
