# Generated by Django 5.2.16 on 2026-08-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objetos_perdidos", "0003_remove_objetoperdido_lugar_resguardo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidenciapropiedad",
            name="archivo",
            field=models.FileField(
                max_length=500, upload_to="objetos_perdidos/evidencias/"
            ),
        ),
        migrations.AlterField(
            model_name="objetoperdido",
            name="imagen",
            field=models.ImageField(
                blank=True, max_length=500, upload_to="objetos_perdidos/"
            ),
        ),
    ]
