# Generated by Django 5.2.16 on 2026-08-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objetos_perdidos", "0004_objetoperdidoimagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objetoperdido",
            name="imagen",
            field=models.ImageField(
                blank=True, max_length=500, upload_to="objetos_perdidos/"
            ),
        ),
        migrations.AlterField(
            model_name="objetoperdidoimagen",
            name="imagen",
            field=models.ImageField(
                max_length=500, upload_to="objetos_perdidos/galeria/"
            ),
        ),
    ]
