# Generated by Django 5.2.16 on 2026-07-17 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="casa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="perfiles",
                to="communities.casa",
            ),
        ),
    ]
