# Generated by Django 5.2.16 on 2026-07-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfil_casa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
    ]
