# Generated by Django 5.2.16 on 2026-07-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
