# Generated by Django 5.2.16 on 2026-07-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfil_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
