# Generated by Django 5.2.16 on 2026-07-17 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categorias', models.CharField(db_index=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('num_tel', models.CharField(blank=True, max_length=30)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('imagenes', models.ImageField(blank=True, upload_to='directorio/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('privada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directorio', to='communities.privada')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrada del directorio',
                'verbose_name_plural': 'entradas del directorio',
                'ordering': ('nombre',),
                'permissions': (('can_create_directory', 'Can create directory'),),
                'indexes': [models.Index(fields=['privada', 'categorias'], name='directorio__privada_2f389c_idx')],
                'constraints': [models.UniqueConstraint(fields=('privada', 'nombre'), name='uq_directorio_privada_nombre')],
            },
        ),
    ]
