# Generated by Django 5.2.16 on 2026-08-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directorio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directorio",
            name="imagenes",
            field=models.ImageField(
                blank=True, max_length=500, upload_to="directorio/"
            ),
        ),
    ]
