# Generated by Django 5.2.17 on 2026-08-20 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directorio',
            name='direccion_externa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='directorio',
            name='maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='directorio',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='directorio',
            name='tipo_ubicacion',
            field=models.CharField(choices=[('local', 'Local'), ('externo', 'Externo')], default='local', max_length=12),
        ),
        migrations.CreateModel(
            name='DirectorioImagen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='directorio/galeria/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('directorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='directorio.directorio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
