# Generated by Django 5.2.16 on 2026-08-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "directorio",
            "0002_directorio_direccion_externa_directorio_maps_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="directorio",
            name="imagenes",
            field=models.ImageField(
                blank=True, max_length=500, upload_to="directorio/"
            ),
        ),
        migrations.AlterField(
            model_name="directorioimagen",
            name="imagen",
            field=models.ImageField(max_length=500, upload_to="directorio/galeria/"),
        ),
    ]
