# Generated by Django 5.2.16 on 2026-08-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_proyecto_imagen_proyectoimagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="imagen",
            field=models.ImageField(blank=True, max_length=500, upload_to="proyectos/"),
        ),
        migrations.AlterField(
            model_name="proyectoimagen",
            name="imagen",
            field=models.ImageField(max_length=500, upload_to="proyectos/galeria/"),
        ),
    ]
