# Generated by Django 5.2.16 on 2026-08-01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communities", "0005_catalogo_modulos_sistema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("activo", "Activo"), ("suspendido", "Suspendido"), ("eliminado", "Eliminado")], db_index=True, default="activo", max_length=12)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("updated_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("titulo", models.CharField(max_length=180)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_inicio", models.DateTimeField(db_index=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("ubicacion", models.CharField(blank=True, max_length=255)),
                ("capacidad", models.PositiveIntegerField(blank=True, null=True)),
                ("imagen", models.ImageField(blank=True, upload_to="eventos/")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("privada", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="eventos", to="communities.privada")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
                "ordering": ("fecha_inicio", "titulo"),
                "indexes": [models.Index(fields=["privada", "fecha_inicio"], name="eventos_eve_privada_fc7d97_idx")],
            },
        ),
    ]
