# Generated by Django 5.2.16 on 2026-08-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_eventoimagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="imagen",
            field=models.ImageField(blank=True, max_length=500, upload_to="eventos/"),
        ),
        migrations.AlterField(
            model_name="eventoimagen",
            name="imagen",
            field=models.ImageField(max_length=500, upload_to="eventos/galeria/"),
        ),
    ]
