# Generated by Django 5.2.16 on 2026-07-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_catalogo_modulos_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='privadamiembro',
            name='inactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
