# Generated by Django 5.2.16 on 2026-08-01 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_reemplazar_encuestas_por_minutas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('privada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reglamento', to='communities.privada')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reglamento',
                'verbose_name_plural': 'reglamentos',
            },
        ),
    ]
