# Generated by Django 5.2.16 on 2026-07-17 04:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('clave', models.CharField(max_length=80, unique=True)),
                ('cuenta', models.CharField(blank=True, max_length=120)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('nombre', models.CharField(max_length=180)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('privada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='communities.privada')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuota',
                'verbose_name_plural': 'cuotas',
                'ordering': ('-fecha_vencimiento',),
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('num', models.PositiveIntegerField(unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='pendiente', max_length=20)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('comprobante', models.ImageField(blank=True, upload_to='pagos/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pagos.cuota')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL)),
                ('privada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='communities.privada')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ('-created_at',),
                'permissions': (('can_validate_payments', 'Can validate payments'),),
            },
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['privada', 'fecha_vencimiento'], name='pagos_cuota_privada_5dd27a_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cuota', 'estado'], name='pagos_pago_cuota_i_bc7c89_idx'),
        ),
    ]
