# Generated by Django 5.2.16 on 2026-07-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado'), ('no_pagado', 'No pagado')], db_index=True, default='pendiente', max_length=20),
        ),
    ]
