# Generated by Django 5.2.16 on 2026-07-17 04:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('num', models.PositiveIntegerField(unique=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('prioridad', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], db_index=True, default='abierto', max_length=20)),
                ('fecha_suceso', models.DateField(blank=True, null=True)),
                ('hora_suceso', models.TimeField(blank=True, null=True)),
                ('evidencia', models.ImageField(blank=True, upload_to='reportes/')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('privada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='communities.privada')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_supervisados', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'ordering': ('-created_at',),
                'permissions': (('can_view_reports', 'Can view reports'), ('can_manage_reports', 'Can manage reports')),
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('num', models.PositiveIntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('seguridad', 'Seguridad'), ('mantenimiento', 'Mantenimiento'), ('servicios', 'Servicios'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('evidencia', models.ImageField(blank=True, upload_to='incidentes/')),
                ('prioridad', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(blank=True, max_length=30)),
                ('fecha_incidente', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('privada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='communities.privada')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'incidente',
                'verbose_name_plural': 'incidentes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['privada', 'estado'], name='reportes_re_privada_accd26_idx'),
        ),
    ]
