# Generated by Django 5.2.16 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0002_alter_incidente_tipo_alter_reporte_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporte",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_proceso", "En proceso"),
                    ("resuelto", "Resuelto"),
                    ("concluido", "Concluido"),
                ],
                db_index=True,
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
