# Generated by Django 5.2.16 on 2026-07-29 08:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reporte_estado_concluido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='descripcion',
            field=models.TextField(default='Sin descripción', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='incidente',
            name='titulo',
            field=models.CharField(default='Incidente', max_length=180),
        ),
        migrations.AddField(
            model_name='reporte',
            name='incidente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporte_seguimiento', to='reportes.incidente'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto')], db_index=True, default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='evidencia',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='fecha_incidente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=30),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='evidencia',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha_suceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipo_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='reportes.tiporeporte'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='reportes.tiporeporte'),
        ),
    ]
