# Generated by Django 5.2.16 on 2026-07-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_seed_tipos_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='incidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_seguimiento', to='reportes.incidente'),
        ),
    ]
