# Generated by Django 5.2.16 on 2026-08-01 20:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0007_reemplazar_encuestas_por_minutas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('eliminado', 'Eliminado')], db_index=True, default='activo', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=180)),
                ('tipo_reunion', models.CharField(choices=[('ordinaria', 'Ordinaria'), ('extraordinaria', 'Extraordinaria'), ('comite', 'Comité')], default='ordinaria', max_length=20)),
                ('fecha_reunion', models.DateTimeField()),
                ('lugar', models.CharField(max_length=180)),
                ('objetivo', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('asistentes', models.TextField(help_text='Un nombre por línea')),
                ('orden_dia', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('acuerdos', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('compromisos', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('proxima_reunion', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('moderador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minutas_creadas', to=settings.AUTH_USER_MODEL)),
                ('privada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minutas', to='communities.privada')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_reunion', '-created_at'),
                'indexes': [models.Index(fields=['privada', 'fecha_reunion'], name='minutas_min_privada_f674b8_idx')],
                'constraints': [models.UniqueConstraint(fields=('privada', 'numero'), name='uq_minuta_numero_privada')],
            },
        ),
    ]
