# Generated by Django 5.2.16 on 2026-08-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areacomunitaria",
            name="imagen",
            field=models.ImageField(blank=True, max_length=500, upload_to="areas/"),
        ),
    ]
