# Generated by Django 5.2.16 on 2026-08-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0002_areaimagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areacomunitaria",
            name="imagen",
            field=models.ImageField(blank=True, max_length=500, upload_to="areas/"),
        ),
        migrations.AlterField(
            model_name="areaimagen",
            name="imagen",
            field=models.ImageField(max_length=500, upload_to="areas/galeria/"),
        ),
    ]
